### ISSUE TITLE
Chain not working on some Sketch docs

### ISSUE THREAD

**Issue by sashagolds** [LaloMrtnz/Chain#10]
Chain will function (i.e. shift colors of elements based on parent, although this also is behaving strangely, as noted in another issue) on some sketch docs, but not on other sketch documents. This persists even after I try to "update" chains.

I've tried uninstalling and reinstalling, as well as restarting Sketch. Running sketch 46.2.

See https://cl.ly/2b3S1D3Z042W

**Comment by LaloMrtnz** [comment]
Hi @sashagolds 
This is exactly the same problem as the one you explained on issue #9. You're chaining the hue property, and color gray has saturation of 0. This means the hue will not show, thus creating the behavior you specified on your video. Again, if you check issue #4, you can find a better explanation.

**Comment by sashagolds** [comment]
@LaloMrtnz Ahh I see. Thanks for the help!

Just to clarify — there is no way to have hue, brightness, AND saturation chained to the same element. Correct?

**Comment by LaloMrtnz** [comment]
Yes you can! You can create a chain to the same element for each of the properties. There's no way to do it on a single chain in this release, but if you create one for hue, one for brightness, and one for saturation you can achieve what you want.

**Comment by sashagolds** [comment]
@LaloMrtnz Thanks!
