### ISSUE TITLE
Bug - Chain is not functioning in Sketch

### ISSUE THREAD

**Issue by EstelleRigault** [LaloMrtnz/Chain#2]
Hi @LaloMrtnz – thanks for putting your time and effort into what looks like a great plugin. And congratulations on getting featured on ProductHunt!

I seem to be having an issue with Chain where I can install the plugin but the Chain window does not appear after clicking Plugins > Chain > New Chain (or any option). 

I have reinstalled the plugin, restarted my computer and sketch, disabled all plugins except Chain, and have updated Sketch. I am on the latest version of Sketch (45.2). 

I hope this information helps :)

**Comment by LaloMrtnz** [comment]
Hi, @EstelleRigault and thanks a lot for installing and supporting Chain. 

Just to make sure, are you selecting _at least_ two layers before running the command? 
If you do that and Chain is still not working, can you please send me your logs? 

To do that: 
**1**. Go to your _Utilities_ folder inside your _Applications_ folder and open the app **Console**
**2**. Inside the Console app, go to the search bar on the top right corner, type *Sketch* and hit return. (That will show only the logs related to Sketch)
**3**. Try running the plugin again, the logs should change. 
**4**. Please copy and paste those logs here to see what's failing. 

If you have any doubt, I'll be glad to help. 😉

**Comment by EstelleRigault** [comment]
Hi, thanks for the quick response. 

Here's the log: 
```
29/07/2017 1:52:09.670 PM New Chain (Sketch)[47977]: SyntaxError: Unexpected identifier 'removeItemFromArray'.
Plugin “Chain”, line 4:
» let removeItemFromArray = function(array, item){
29/07/2017 1:52:09.670 PM Sketch[47977]: Exception: {
    line = 4;
    sourceURL = "/Users/ajh/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Chain.sketchplugin/Contents/Sketch/Chain.cocoascript";
}
```

**Comment by LaloMrtnz** [comment]
That's weird, that log message makes no sense given the context you're telling me. 

Can you please try to uninstall the plugin, then [redownload](https://github.com/LaloMrtnz/Chain/releases/latest) and reinstall it? I'm sorry but if you have not created any previous chains, that should be the problem

**Comment by stephanedelgado** [comment]
Hi @LaloMrtnz – great plugin, would love to use it. 
I am on the latest version of Sketch (45.2) and New Chain command doesn't open any modal
Here are the logs:

```
30/7/2017 6:22:57.367 PM New Chain (Sketch)[17550]: SyntaxError: Unexpected identifier 
'removeItemFromArray'.
Plugin “Chain”, line 4:
» let removeItemFromArray = function(array, item){
```
```
30/7/2017 6:29:03.294 PM Sketch[17550]: Exception: {
    line = 4;
    sourceURL = "/Users/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Chain.sketchplugin/Contents/Sketch/Chain.cocoascript";
}
```

**Comment by LaloMrtnz** [comment]
Hello, @stephanedelgado. Reinstalling the plugin is not working? 
I've been trying really hard to replicate the bug, but I haven't been able to do so. Could you help giving more information?

**Comment by haziqmir** [comment]
Hey @LaloMrtnz, here is what I got:

31/07/17 7:30:31.964 AM New Chain (Sketch)[23404]: SyntaxError: Unexpected identifier 'removeItemFromArray'.
Plugin “Chain”, line 4:
» let removeItemFromArray = function(array, item){

31/07/17 7:30:31.964 AM Sketch[23404]: Exception: {
    line = 4;
    sourceURL = "/Users/haziqmir/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Chain.sketchplugin/Contents/Sketch/Chain.cocoascript";
}

**Comment by alekspetrov** [comment]
Sketch V45.2
Trying to chain selected layers and nothing happens, chaining not working. 

Log:
![screen shot 2017-07-31 at 12 17 46](https://user-images.githubusercontent.com/5360806/28760427-66203776-75ea-11e7-8d1b-54d5c16e5db6.png)

**Comment by LaloMrtnz** [comment]
You're all having the same issue but I still cannot replicate it. Have you all tried **resinstalling it**? 

Also, can you please specify if you have created Chains before experiencing the problem and what kind of layers you're trying to chain?

**Comment by haziqmir** [comment]
@LaloMrtnz I did reinstall the plugin. I went as far as to disable all other plugins but Chain, yet it didn't work. I have not been able to create any Chains so far.

**Comment by LaloMrtnz** [comment]
Guys, @haziqmir [mentioned](https://twitter.com/haziqmir/status/890869930710540288) he's not using the latest OSX,  at first I thought that should be a problem, but I'm not really sure now. 

Can you all share what OS version you're using?

**Comment by alekspetrov** [comment]
Sierra 10.12.6

**Comment by LaloMrtnz** [comment]
@alekspetrov  Your logs are not the same as everybody else's. Can you see the modal screen where you select the options after clicking _New Chain_?

**Comment by alekspetrov** [comment]
@LaloMrtnz yes, I can see options window, but clicking to "chain" do nothing

**Comment by LaloMrtnz** [comment]
@alekspetrov alright, then your problem is different. Would you mind opening a [New Issue](https://github.com/LaloMrtnz/Chain/issues/new) explaining your situation?
Please make include the color of the layers you're trying to chain, and the properties you're setting on the selection screen (the type of chain, the properties you're chaining [fill/border], and the value you're entering.

**Comment by inetwebguy** [comment]
SAME ISSUE
OXS 10.11.3 -I can't update the OS on my work laptop, but can on mine at home. Wil try tonight and confirm if I have the same bug

**Comment by stephanedelgado** [comment]
Sketch version 46.1 running on OSX 10.11.6
Deleted then re-installed latest plug-in, created two rectangles (one grey and one red). Having both rectangles selected, command-shift-C does nothing.

```
12/8/2017 2:56:39.556 PM Sketch[47689]: Exception: {
    line = 4;
    sourceURL = "/Users/stephanedelgado/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Chain.sketchplugin/Contents/Sketch/Chain.cocoascript";
}
```

**Comment by LaloMrtnz** [comment]
Hey, guys, the plugin **is updated now** to work with ES5, which I think is the problem based on the feedback you provided. 

You can [download it now](https://github.com/LaloMrtnz/Chain/releases/tag/v0.9.2) from Github or simply update it through Sketch.
