### ISSUE TITLE
Plugin Not Chaining shapes

### ISSUE THREAD

**Issue by alekspetrov** [LaloMrtnz/Chain#3]
Spec:
Mac OS Sierra 10.12.6
Sketchapp 45.2

Steps: 
1. Create 3 shape and select them
2. Plugins > Chain > New Chain
3. Chaining dialog setings: 
<img width="428" alt="screen shot 2017-08-01 at 09 02 39" src="https://user-images.githubusercontent.com/5360806/28802132-534bc6de-7698-11e7-98c0-c95ad049addc.png">
4. Click on "Chain" and nothing has changed

Thanks for supporting

**Comment by LaloMrtnz** [comment]
@alekspetrov Are any of the layers gray?

**Comment by alekspetrov** [comment]
Updated plugin from 0.9 to 0.9.1 and it works fine! =) Thanks!
